name: Ronin Test Data Generator Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install DataDog CI
        shell: bash
        run: npm install -g @datadog/datadog-ci
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test
        uses: projectronin/github/.github/actions/basic-gradle-build-publish@basic_gradle_build_publish/v2
        with:
          nexus_user: ${{ secrets.NEXUS_MAVEN_USER }}
          nexus_token: ${{ secrets.NEXUS_MAVEN_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          publish: false
          dd-api-key: ${{ secrets.DATADOG_API_KEY }}
          dd-service-name: ronin-test-utilities
